#Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
#install.packages("")
#devtools::install_github("an-bui/calecopal")

library(data.table)
library(janitor)
library(here)
library(tidyverse)
library(lubridate)
library(readxl)
library(gridExtra)
#library(calecopal)
library(rstatix)
library(vars)
library(MuMIn)
library(lme4) #for mixed effects models
library(arm)
library(nlme)
select = dplyr::select

source(here::here("scripts", "scripts_functions", "figure_info.R"))

#datver <- "20230724"
#dataversion <- paste0("Data_", datver)
```
#Sample sizes: 

```{r}
data_bothspp_raw <- read_csv(here::here("processed-data", paste0("analysis_bothspp",datver,".csv")), show_col_types = FALSE) %>% 
  #filter(species == "live oak") %>% 
  distinct() %>% 
  mutate(week = case_when(
    date_wp %in% c("2022-03-15") ~ 11, 
    TRUE ~ as.numeric(week)
  )) %>% 
  select(-plot) %>% 
  distinct() %>% 
  filter(lwc_mean < 2) %>% 
  filter(!(week == 33)) #only have 2 middays here
 
sample_sizes <- data_bothspp_raw  %>% 
  group_by(species, week, date_wp, time) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = c("species"), values_from = c("n")) 

sample_sizes

sample_sizes %>% 
  write_csv(here("figures", "sample_size.csv"))
```

```{r}
df <- read_csv(here("processed-data", paste0("wp_wc_rwc_",datver,".csv"))) %>% 
  select(species, week, date_wp, time, tree) %>% 
  distinct()

df %>% 
  group_by(species, week, date_wp, time) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = c("species"), values_from = c("n")) 
```


#TIMELINE: 
```{r, fig.height=5, fig.width=6}
wc_qudo_df <- read_csv(here::here("processed-data", paste0("analysis",datver,".csv")), show_col_types = FALSE) %>% 
 # filter(species == "live oak") %>% 
  distinct() %>% 
 # group_by(week, time) %>% 
 # filter(n() >= 10) %>% #only run on weeks where we have a decent number of samples
#  ungroup() %>% 
#  filter(!week == 21) %>% #this week doesn't have very many samples,
  mutate(time_season = case_when(
    week  <= 17 ~ "before leafout", 
    week > 17 ~ "after leafout", 
    TRUE ~ as.character("none")
  )) %>% 
  select(-plot) %>% 
  distinct() %>% 
  filter(!(week == 19 & time == "pd" & water_potential < -2))%>% 
  filter(!(week == 11)) %>% 
  drop_na(water_potential) 

wc_qudo_df%>% 
  ggplot(aes(x = week, y = 0, color = water_potential))+
  geom_hline(yintercept = 0) + 
  geom_point(size = 5) +
  facet_wrap(~time) + 
  color_grad_rev +
  labs(color = "Water Potential 
       (MPa)")+
  theme(legend.position = "right", 
        axis.title.y = element_blank(), 
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
       legend.title.align = -.5,
       legend.direction = "vertical",
       legend.key.size = unit(1, "cm")
        )

timeline_df <- wc_qudo_df %>% 
 # select(week, date_wp, time) %>% 
  mutate(date_new = case_when(
    date_wp %in% c("2022-03-08") ~ "2022-03-08",#CWC also measured on March 15th, keep
    date_wp %in% c("2022-03-15") ~ "2022-03-16", #overflight on 3/16
    date_wp %in% c("2022-03-23", "2022-03-25") ~ "2022-03-22", #ok to combine these, CWC only measured on March 222, some MPas on March 23
    date_wp %in% c("2022-03-30","2022-04-06","2022-04-04") ~ "2022-04-05", #CWC also measured on April 06, just use 04-04
    date_wp %in% c("2022-04-13", "2022-04-11") ~ "2022-04-12", #CWC also measred on April 11, just keep 
    date_wp %in% c("2022-04-20") ~ "2022-04-20", #
    date_wp %in% c("2022-04-27", "2022-04-25") ~ "2022-04-29", #
    date_wp %in% c("2022-05-04") ~ "2022-05-03",
    date_wp %in% c("2022-05-09") ~ "2022-05-11",
    date_wp %in% c("2022-05-09") ~ "2022-05-17", #might not have MPas?
    date_wp %in% c("2022-05-23", "2022-05-25") ~ "2022-05-29",
    TRUE ~ as.character(date_wp)
  )) %>% 
  mutate(date_new = ymd(date_new)) %>% 
  select(date_new, week, water_potential, time) %>% 
  distinct()


timeline_plot <- timeline_df %>% 
  drop_na(water_potential) %>% 
  filter(time == "md") %>% 
  ggplot(aes(x = date_new, 
             y = 0, 
             color = water_potential))+
  geom_hline(yintercept = 0) +
  geom_point(size = 10) +
    geom_point(data= timeline_df %>% 
               filter(week %in% c(10, 11, 12, 14,15, 17, 18, 19, 21, 37)), 
           pch=21, 
           size=10, 
           stroke=2,
           colour="black") +
  color_grad_rev+
  ylim(-.25, +.25)  + 
  theme(legend.position = "none", 
        axis.title.y = element_blank(), 
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=.5, size= 20)
        ) +
# scale_x_date(date_labels = '%b. %d',
#              breaks = as.Date(c("2022-03-08",#"2022-03-15", 
#                                 "2022-03-25", 
#                                 #"2022-03-23", "2022-03-30", 
#                                 "2022-04-04", #"2022-04-06","2022-04-13", 
#                                 "2022-04-11", #"2022-04-27", 
#                                 "2022-04-25", #"2022-05-04" ,
#                                 "2022-05-09", "2022-05-23", 
#                                 #"2022-05-23", 
#                                 "2022-07-19", "2022-08-18","2022-09-15")))  +
  scale_x_date(breaks = unique(timeline_df$date_new), 
               date_labels = '%b. %d')
timeline_plot

ggsave(here("figures", "timeline_plot"), timeline_plot, device = "jpg", width = 12, height = 2, dpi = 300)
```

DATA
```{r}
timeline_df <- wc_qudo_df %>% 
 # select(week, date_wp, time) %>% 
  mutate(date_wp = as.character(date_wp)) %>% 
  mutate(date_new = case_when(
    date_wp %in% c("2022-03-15") ~ "2022-03-08",
    date_wp %in% c("2022-03-23") ~ "2022-03-25",
    date_wp %in% c("2022-03-30","2022-04-06") ~ "2022-04-05",
    date_wp %in% c("2022-04-13") ~ "2022-04-11",
    date_wp %in% c("2022-04-27") ~ "2022-04-25",
    date_wp %in% c("2022-05-04") ~ "2022-05-09",
    date_wp %in% c("2022-05-23") ~ "2022-05-25",
    TRUE ~ as.character(date_wp)
  )) %>% 
  mutate(date_new = ymd(date_new)) %>% 
  select(date_new, week, water_potential, time,date_wp) %>% 
  distinct() %>%
#Dates below are so that the colors line up with the cwc outlines on the timeline; comment them out if we want to have the actual MPa dates (so that the points are offset from the outlines)
  mutate(date_new = case_when(
   # date_wp %in% c("2022-03-15") ~ "2022-03-08",#CWC also measured on March 15th, keep
    date_wp %in% c("2022-03-15") ~ "2022-03-16", #overflight on 3/16
    date_wp %in% c("2022-03-23", "2022-03-25") ~ "2022-03-22", #ok to combine these, CWC only measured on March 222, some MPas on March 23
    date_wp %in% c("2022-03-30","2022-04-06","2022-04-04") ~ "2022-04-05", #CWC also measured on April 06, just use 04-04
    date_wp %in% c("2022-04-13", "2022-04-11") ~ "2022-04-12", #CWC also measred on April 11, just keep 
    date_wp %in% c("2022-04-20") ~ "2022-04-20", #
    date_wp %in% c("2022-04-27", "2022-04-25") ~ "2022-04-29", #
    date_wp %in% c("2022-05-04") ~ "2022-05-03",
    date_wp %in% c("2022-05-09") ~ "2022-05-11",
    date_wp %in% c("2022-05-09") ~ "2022-05-17", #might not have MPas?
    date_wp %in% c("2022-05-23", "2022-05-25") ~ "2022-05-29",
    TRUE ~ as.character(date_wp)
  )) %>% 
  mutate(date_new = ymd(date_new))


#For CWC
data_og_cwc1 <- read_csv(here("processed-data", paste0("cwc_analysis",datver,".csv")), show_col_types = F) %>%  
  filter(species %in% c("live oak")) %>% 
  select(tree, week, water_potential, cwc, time_season, time, site, date_wp) %>% 
  mutate(water_potential = -1*water_potential) %>% 
  distinct() %>% 
   # filter(!tree %in% c(2012, 2011)) %>% 
  filter(!(tree %in% c(2346))) 

data_og_cwc <- data_og_cwc1 %>% #this tree seems to have a problem with post-leafout cwc - all 0s - likely becuase the canopy was too small to see. 
  filter(!week %in% c(9)) %>%  #week 11 only has 9 midday measurements and acts really odd (2022-03-15), 9 just had 3 measurements
  select(tree, week, date_wp, cwc, time_season)  %>% 
  mutate(date_new = case_when(
   # date_wp %in% c("2022-03-15") ~ "2022-03-08",#CWC also measured on March 15th, keep
    date_wp %in% c("2022-03-15") ~ "2022-03-16", #overflight on 3/16
    date_wp %in% c("2022-03-23", "2022-03-25") ~ "2022-03-22", #ok to combine these, CWC only measured on March 222, some MPas on March 23
    date_wp %in% c("2022-03-30","2022-04-06","2022-04-04") ~ "2022-04-05", #CWC also measured on April 06, just use 04-04
    date_wp %in% c("2022-04-13", "2022-04-11") ~ "2022-04-12", #CWC also measred on April 11, just keep 
    date_wp %in% c("2022-04-20") ~ "2022-04-20", #
    date_wp %in% c("2022-04-27", "2022-04-25") ~ "2022-04-29", #
    date_wp %in% c("2022-05-04") ~ "2022-05-03",
    date_wp %in% c("2022-05-09") ~ "2022-05-11",
    date_wp %in% c("2022-05-09") ~ "2022-05-17", #might not have MPas?
    date_wp %in% c("2022-05-23", "2022-05-25") ~ "2022-05-29",
    TRUE ~ as.character(date_wp)
  )) %>% 
  add_row(date_new = "2022-05-17", cwc = 1)
```


With all dates: 
```{r}
ggplot() +
  geom_hline(yintercept = 0) +
  geom_point(aes(x = date_new, 
             y = 0, 
             color = water_potential),
             data = timeline_df %>% drop_na(water_potential) %>% filter(time == "md"), 
             size = 10,
            # pch=21, 
           size=10) +
    geom_point(aes(x = date_new,
             y = 0),
            data = data_og_cwc %>% drop_na(cwc) %>% mutate(date_new = ymd(date_new)) %>% filter(!(date_new %in% c("2022-02-28"))),
           pch=21,
           size=10,
           stroke=2,
           colour="black") +
  color_grad_rev+
  ylim(-.25, +.25)  + 
  theme(legend.position = "none", 
        axis.title.y = element_blank(), 
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=.5, size= 20)
        ) +
scale_x_date(date_labels = '%b. %d', 
             breaks = as.Date(data_og_cwc$date_new))
```
             
```{r}
ggplot() +
  geom_hline(yintercept = 0) +
  geom_point(aes(x = date_new, 
             y = 0, 
             color = water_potential),
             data = timeline_df %>% drop_na(water_potential) %>% filter(time == "md"), 
             size = 10,
            # pch=21, 
           size=10) +
    geom_point(aes(x = date_new,
             y = 0),
            data = data_og_cwc %>% drop_na(cwc) %>% mutate(date_new = ymd(date_new)) %>% filter(!(date_new %in% c("2022-02-28"))),
           pch=21,
           size=10,
           stroke=2,
           colour="black") +
  color_grad_rev+
  ylim(-.25, +.25)  + 
  theme(legend.position = "none", 
        axis.title.y = element_blank(), 
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.x = element_text(angle = 60, vjust = 0.5, hjust=.5, size= 20)
        ) +
scale_x_date(date_labels = '%b. %d', 
             breaks = as.Date(data_og_cwc1$date_new))
```
#PHENOLOGY: 

```{r}
data_qudo_raw <- read_csv(here::here("processed-data", paste0("analysis",datver,".csv")), show_col_types = FALSE) %>% 
 # filter(species == "live oak") %>% 
  distinct() %>% 
 # group_by(week, time) %>% 
 # filter(n() >= 10) %>% #only run on weeks where we have a decent number of samples
#  ungroup() %>% 
#  filter(!week == 21) %>% #this week doesn't have very many samples,
  mutate(time_season = case_when(
    week  <= 17 ~ "before leafout", 
    week > 17 ~ "after leafout", 
    TRUE ~ as.character("none")
  )) %>% 
    mutate(week = case_when(
    date_wp %in% c("2022-03-15") ~ 11, 
    TRUE ~ as.numeric(week)
  )) %>% 
  select(-plot) %>% 
  distinct() %>% 
  filter(!(week == 19 & time == "pd" & water_potential < -2)) 

data_qudo_raw %>% 
  ggplot(aes(y = alas_cm2_per_mm2, 
             x = date_wp)) +
  geom_point()  +
  scale_x_date(breaks = unique(data_qudo_raw$date_wp), 
               date_labels = "%Y-%m-%d") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

data_qudo_raw %>% 
  ggplot(aes(y = lma_g_cm2, 
             x = date_wp)) +
  geom_jitter()  +
  scale_x_date(breaks = unique(data_qudo_raw$date_wp), 
               date_labels = "%Y-%m-%d") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


fig <- data_qudo_raw %>% 
  ggplot(aes(y = alas_cm2_per_mm2, 
             x = date_wp)) +
  geom_point()  +
  scale_x_date(breaks = unique(data_qudo_raw$date_wp), 
               date_labels = "%Y-%m-%d") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "Al:As (cm2/cm2)")

fig
ggsave(here("figures", "qudo figures", "alas_long_plot"), fig, device = "jpeg", width = 8, height = 5, dpi = 300)
```
```{r}
lma_plot_df <- read_csv(here::here("processed-data", paste0("analysis",datver,".csv")), show_col_types = FALSE)  %>% 
  select(alas_cm2_per_mm2, species, week, week_alas_link, swc_per_dry_g_mean, date_wp) %>% 
  rename(mean_swc_per_dry_g = swc_per_dry_g_mean) 

# Calculate means and variation (standard deviation or standard error)
lma_plot_summary <- lma_plot_df %>%
  mutate(week_alas_link = case_when(
    week_alas_link %in% c(11) ~ 10, 
    week_alas_link %in% c(13) ~ 14, 
    TRUE ~ as.numeric(week_alas_link)
  )) %>% 
  mutate(date_wp = case_when(
    date_wp %in% c("2022-03-15") ~ as.Date("2022-03-08"), 
    date_wp %in% c("2022-04-06") ~ as.Date("2022-04-04"), 
    date_wp %in% c("2022-04-13") ~ as.Date("2022-04-11"), 
    TRUE ~ as.Date(date_wp)
  ))%>%
  group_by(species, date_wp) %>%
  summarise(
    mean_lma = mean(alas_cm2_per_mm2, na.rm = TRUE),
    sd_lma = sd(alas_cm2_per_mm2, na.rm = TRUE),
    mean_swc = mean(mean_swc_per_dry_g, na.rm = TRUE),
    sd_swc = sd(mean_swc_per_dry_g, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    se_lma = sd_lma / sqrt(n()),
    se_swc = sd_swc / sqrt(n())
  ) %>%
  filter(species %in% c("blue oak")) %>% 
  mutate(date_wp = as.Date(date_wp)) 

# Plot with error bars
lma_plot <- lma_plot_summary %>% 
  ggplot() +
  geom_line(aes(x = date_wp, y = mean_lma)) +
  geom_errorbar(aes(
    x = date_wp,
    ymin = (mean_lma - sd_lma),
    ymax = (mean_lma + sd_lma)
  ), width = 0, color = "black") +
    geom_point(aes(x = date_wp, 
                   y = mean_lma), 
               size = 3)  +
  scale_x_date(breaks = unique(lma_plot_summary$date_wp), 
               date_labels = "%Y-%m-%d") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "Al:As (cm2)")
lma_plot
```

#Phenology timelines
```{r, fig.height=2, fig.width=6}
##USE THIS ONE: 
#lma_plot <- data_qudo_raw %>% 
lma_plot_df <- read_csv(here("processed-data", paste0("wp_wc_rwc_",datver,".csv")))  %>% 
    select(mean_swc_per_dry_g, lma_g_cm2, species, week, week_alas_link, year_rwc) %>% 
  drop_na(mean_swc_per_dry_g) 

lma_plot_df  %>% 
  mutate(week_alas_link = case_when(
    week_alas_link %in% c(11) ~ 10, 
    week_alas_link %in% c(13) ~ 14, 
    TRUE ~ as.numeric(week_alas_link)
  )) %>% 
    group_by(week_alas_link, species) %>% 
  # mutate(mean_swc_per_dry_g  = scale(mean_swc_per_dry_g), 
  #        lma_g_cm2 = scale(lma_g_cm2)) %>% 
  select(mean_swc_per_dry_g, lma_g_cm2, species, week, year_rwc) %>% 
  mutate(#lma_all = lma_g_cm2_new,
         lma_g_cm2 = mean(lma_g_cm2, na.rm = T), 
         mean_swc_per_dry_g = mean(mean_swc_per_dry_g, na.rm = T)) %>% 
  #filter(species %in% c("blue oak")) %>% 
  #filter(lma_g_cm2 < 0.08) %>% 
  select(week, #species, 
         lma_g_cm2,
          mean_swc_per_dry_g) %>% 
  distinct() %>% 
  drop_na(lma_g_cm2)  %>%
 # filter(week %in% c(10, 11, 13, 14, 17, 21, 29, 37, 40)) %>% 
  ggplot() +
  # geom_point(aes(x = week_alas_link, 
  #            y = lma_g_cm2, 
  #            #color = species
  #            ),
  #            size = 3) +
  # geom_line(aes(x = week_alas_link, 
  #            y = lma_g_cm2, 
  #            #color = species
  #            )) +
  geom_point(aes(x = week_alas_link, 
             y = mean_swc_per_dry_g, 
             color = "darkgrey",
             shape = year_rwc
             #color = species
             ),
                shape = 17,
             size = 3,
            color = "darkgrey") +
  geom_line(aes(x = week_alas_link, 
             y =mean_swc_per_dry_g, 
             group = species
             #color = species
             ),
            color = "darkgrey") +
  facet_wrap(~species) +
  labs(y = "Saturated Water Content")
```


```{r, fig.height=2, fig.width=6}
lma_plot <- lma_plot_df  %>% 
  mutate(week_alas_link = case_when(
    week_alas_link %in% c(11) ~ 10, 
    week_alas_link %in% c(13) ~ 14, 
    TRUE ~ as.numeric(week_alas_link)
  )) %>% 
    group_by(week_alas_link, species) %>% 
  # mutate(mean_swc_per_dry_g  = scale(mean_swc_per_dry_g), 
  #        lma_g_cm2 = scale(lma_g_cm2)) %>% 
  select(mean_swc_per_dry_g, lma_g_cm2, species, week, year_rwc) %>% 
  mutate(#lma_all = lma_g_cm2_new,
         lma_g_cm2 = mean(lma_g_cm2, na.rm = T), 
         mean_swc_per_dry_g = mean(mean_swc_per_dry_g, na.rm = T)) %>% 
  #filter(species %in% c("blue oak")) %>% 
  #filter(lma_g_cm2 < 0.08) %>% 
  select(week, #species, 
         lma_g_cm2,
          mean_swc_per_dry_g) %>% 
  distinct() %>% 
  drop_na(lma_g_cm2)  %>%
 # filter(week %in% c(10, 11, 13, 14, 17, 21, 29, 37, 40)) %>% 
  ggplot() +
  # geom_point(aes(x = week_alas_link, 
  #            y = lma_g_cm2, 
  #            #color = species
  #            ),
  #            size = 3) +
  # geom_line(aes(x = week_alas_link, 
  #            y = lma_g_cm2, 
  #            #color = species
  #            )) +
  geom_point(aes(x = week_alas_link, 
             y = lma_g_cm2, 
             color = "darkgrey",
             shape = year_rwc
             #color = species
             ),
                shape = 17,
             size = 3,
            color = "darkgrey") +
  geom_line(aes(x = week_alas_link, 
             y = lma_g_cm2, 
             group = species
             #color = species
             ),
            color = "darkgrey") +
  facet_wrap(~species) +
  labs(y = "LMA (g/cm2)") +
  theme(legend.position = "none",
        axis.title.y = element_text(size = 20), 
        axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
       # axis.text.x = element_text(hjust=.5, size= 20)
        )
lma_plot

y.grob <- textGrob("SWC (g)", 
                   gp=gpar(col="#525252", 
                           fontsize=20), 
                   rot=90)

lma_swc_plot <- grid.arrange(arrangeGrob(lma_plot,
                            right = y.grob, 
                            #bottom = x.grob1),
                            heights = c(1, 0), 
                            widths = c(1.5, 0)))


ggsave(here("figures", "figures", "Fig 5", "lma_both_spp"), lma_swc_plot, device = "jpeg", width = 12, height = 1.75, dpi = 300)
```


####SWC and LMA: (Use this)

```{r, fig.height=2, fig.width=6}
##USE THIS ONE: 
#lma_plot <- data_qudo_raw %>% 
lma_plot_df <- read_csv(here("processed-data", paste0("wp_wc_rwc_",datver,".csv")))  %>% 
    select(mean_swc_per_dry_g, lma_g_cm2, species, week, week_alas_link, date_wp) %>% 
  drop_na(mean_swc_per_dry_g)

lma_plot_df_dates <- lma_plot_df %>% 
  select(date_wp, week_alas_link) %>% 
  mutate(week_alas_link = case_when(
    week_alas_link %in% c(11) ~ 10, 
    week_alas_link %in% c(13) ~ 14, 
    TRUE ~ as.numeric(week_alas_link)
  )) %>% 
  distinct()
```


```{r, fig.height=2, fig.width=6}
unique(lma_plot_df$date_wp)

lma_plot <- lma_plot_df  %>% 
  mutate(week_alas_link = case_when(
    week_alas_link %in% c(11) ~ 10, 
    week_alas_link %in% c(13) ~ 14, 
    TRUE ~ as.numeric(week_alas_link)
  )) %>% 
    group_by(week_alas_link, species) %>% 
  # mutate(mean_swc_per_dry_g  = scale(mean_swc_per_dry_g), 
  #        lma_g_cm2 = scale(lma_g_cm2)) %>% 
  select(mean_swc_per_dry_g, lma_g_cm2, species, week) %>% 
  mutate(#lma_all = lma_g_cm2_new,
         lma_g_cm2 = mean(lma_g_cm2, na.rm = T), 
         mean_swc_per_dry_g = mean(mean_swc_per_dry_g, na.rm = T)) %>% 
  filter(species %in% c("blue oak")) %>% 
  #filter(lma_g_cm2 < 0.08) %>% 
  select(week, #species, 
         lma_g_cm2,
          mean_swc_per_dry_g) %>% 
  distinct() %>% 
  drop_na(lma_g_cm2)  %>%
 # filter(week %in% c(10, 11, 13, 14, 17, 21, 29, 37, 40)) %>% 
  ggplot() +
  geom_point(aes(x = week_alas_link, 
             y = lma_g_cm2  * 80, 
             #color = species
             ),
             size = 3) +
  geom_line(aes(x = week_alas_link, 
             y = lma_g_cm2 * 80, 
             #color = species
             )) +
  geom_point(aes(x = week_alas_link, 
             y = mean_swc_per_dry_g, 
             color = "darkgrey"
             #color = species
             ),
                shape = 17,
             size = 3,
            color = "darkgrey") +
  geom_line(aes(x = week_alas_link, 
             y =mean_swc_per_dry_g, 
             group = species
             #color = species
             ),
            color = "darkgrey") +
 # scale_x_continuous(breaks = c(10, 14, 17, 21, 29, 37)) +
  labs(y = "LMA (g/cm2)") +
  theme(legend.position = "none",
        axis.title.y = element_text(size = 20), 
        axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
       # axis.text.x = element_text(hjust=.5, size= 20)
        )
lma_plot

y.grob <- textGrob("SWC (g)", 
                   gp=gpar(col="#525252", 
                           fontsize=20), 
                   rot=90)

lma_swc_plot <- grid.arrange(arrangeGrob(lma_plot,
                            right = y.grob, 
                            #bottom = x.grob1),
                            heights = c(1, 0), 
                            widths = c(1.5, 0)))


ggsave(here("figures", "qudo figures", "lma_long_plot"), lma_swc_plot, device = "jpeg", width = 12, height = 1.75, dpi = 300)
```

```{r}
lma_plot_df <- read_csv(here("processed-data", paste0("wp_wc_rwc_", datver, ".csv"))) %>% 
  select(mean_swc_per_dry_g, lma_g_cm2, species, week, week_alas_link) %>% 
  drop_na(mean_swc_per_dry_g)

# Calculate means and variation (standard deviation or standard error)
lma_plot_summary <- lma_plot_df %>%
  mutate(week_alas_link = case_when(
    week_alas_link %in% c(11) ~ 10, 
    week_alas_link %in% c(13) ~ 14, 
    TRUE ~ as.numeric(week_alas_link)
  )) %>%
  group_by(week_alas_link, species) %>%
  summarise(
    mean_lma = mean(lma_g_cm2, na.rm = TRUE),
    sd_lma = sd(lma_g_cm2, na.rm = TRUE),
    mean_swc = mean(mean_swc_per_dry_g, na.rm = TRUE),
    sd_swc = sd(mean_swc_per_dry_g, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    se_lma = sd_lma / sqrt(n()),
    se_swc = sd_swc / sqrt(n())
  ) %>%
  filter(species %in% c("blue oak"))

# Plot with error bars
lma_plot <- lma_plot_summary %>% 
  ggplot() +
  geom_line(aes(x = week_alas_link, y = mean_lma * 80)) +
  geom_errorbar(aes(
    x = week_alas_link,
    ymin = (mean_lma - sd_lma) * 80,
    ymax = (mean_lma + sd_lma) * 80
  ), width = 0, color = "black") +
   geom_errorbar(aes(
    x = week_alas_link,
    ymin = mean_swc - sd_swc,
    ymax = mean_swc + sd_swc
  ), width = 0, color = "darkgrey") +
  geom_point(aes(x = week_alas_link, y = mean_swc), shape = 17, size = 3, color = "darkgrey") +
    geom_point(aes(x = week_alas_link, y = mean_lma * 80), size = 3) +
  geom_line(aes(x = week_alas_link, y = mean_swc), color = "darkgrey") +
 
  labs(y = "LMA (g/cm2)") +
  theme(
    legend.position = "none",
    axis.title.y = element_text(size = 20), 
    axis.text.x = element_blank(),
    axis.title.x = element_blank(), 
    axis.text.y = element_blank(),
    axis.ticks = element_blank()
  )

# Add secondary axis label
y.grob <- textGrob("SWC (g)", 
                   gp = gpar(col = "#525252", fontsize = 20), 
                   rot = 90)

lma_swc_plot <- grid.arrange(
  arrangeGrob(
    lma_plot,
    right = y.grob, 
    heights = c(1, 0), 
    widths = c(1.5, 0)
  )
)

# Save plot
ggsave(here("figures", "qudo figures", "lma_long_plot"), 
       lma_swc_plot, device = "jpeg", 
       width = 12, height = 1.75, dpi = 300)

```

```{r, fig.height=2, fig.width=6}
##USE THIS ONE: 
#lma_plot <- data_qudo_raw %>% 
lma_plot_df <- read_csv(here("processed-data", paste0("wp_wc_rwc_",datver,".csv"))) %>% 
  #filter(year_alas %in% c(1)) %>% 
  filter(year_rwc %in% c(1))

unique(lma_plot_df$date_rwc)

lma_plot <- lma_plot_df  %>% 
   # select(mean_swc_per_dry_g, lma_g_cm2, species, week, week_alas_link, year_alas,year_rwc) %>% 
  drop_na(mean_swc_per_dry_g) %>% 
  distinct() %>% 
  mutate(week_alas_link = case_when(
    week_alas_link %in% c(11) ~ 10, 
    week_alas_link %in% c(13) ~ 14, 
    TRUE ~ as.numeric(week_alas_link)
  )) %>% 
    group_by(week_alas_link, species#, year_alas, year_rwc
             ) %>% 
  # mutate(mean_swc_per_dry_g  = scale(mean_swc_per_dry_g), 
  #        lma_g_cm2 = scale(lma_g_cm2)) %>% 
 # select(mean_swc_per_dry_g, lma_g_cm2, species, week, year_alas) %>% 
  mutate(#lma_all = lma_g_cm2_new,
         lma_g_cm2 = mean(lma_g_cm2, na.rm = T), 
         mean_swc_per_dry_g = mean(mean_swc_per_dry_g, na.rm = T)
        # year_rwc = as.factor(year_rwc), 
       #  year_alas = as.factor(year_alas)
       ) %>% 
  filter(species %in% c("blue oak")) %>% 
  #filter(lma_g_cm2 < 0.08) %>% 
  # select(week, #species, 
  #        year_alas, 
  #        lma_g_cm2,
  #         mean_swc_per_dry_g) %>% 
  distinct() %>% 
  drop_na(lma_g_cm2)  %>%
 # filter(week %in% c(10, 11, 13, 14, 17, 21, 29, 37, 40)) %>% 
  ggplot() +
  geom_point(aes(x = week_alas_link, 
              #  shape = year_alas, 
             y = lma_g_cm2  * 34, #need a scaling factor to bring lma up to swc
             #color = species
             ),
             size = 3) +
  geom_line(aes(x = week_alas_link, 
             y = lma_g_cm2 * 34, 
           #  line_type = year_alas,
             #color = species
             )) +
  geom_point(aes(x = week_alas_link, 
             y = mean_swc_per_dry_g, 
             color = "darkgrey",
            # shape = year_rwc, 
             #color = species
             ),
                shape = 17,
             size = 3,
            color = "darkgrey") +
  geom_line(aes(x = week_alas_link, 
             y =mean_swc_per_dry_g, 
            # linetype = year_rwc, 
             group = species
             #color = species
             ),
            color = "darkgrey") +
  scale_x_continuous(breaks = c(10, 14, 21, 29, 37)) +
  labs(y = "LMA (g/cm2)", 
       x = "Week") +
  theme(legend.position = "none",
        axis.title.y = element_blank(), 
        axis.title.x = element_blank(),
        axis.text.x = element_blank(), 
       # axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
       # axis.text.x = element_text(hjust=.5, size= 20)
        )
lma_plot

y.grob <- textGrob("SWC (g)", 
                   gp=gpar(col="#525252", 
                           fontsize=20), 
                   rot=90)

y.grob2 <- textGrob("LMA (g/cm2)", 
                   gp=gpar(col="black", 
                           fontsize=20), 
                  
                   rot=90)

lma_swc_plot <- grid.arrange(arrangeGrob(lma_plot,
                            right = y.grob, 
                            left = y.grob2,
                            #bottom = x.grob1),
                            heights = c(1, 0), 
                            widths = c(1.5, 0)))


ggsave(here("figures", "qudo figures", "lma_long_plot_2"), lma_swc_plot, device = "jpeg", width = 6, height = 1.75, dpi = 300)
```


```{r, fig.height=2, fig.width=6}
lma_plot <- read_csv(here("processed-data", paste0("wp_wc_rwc_",datver,".csv")), show_col_types = F) %>%
 # lma_plot <- read_csv(here("processed-data", paste0("analysis",datver,".csv")), show_col_types = F) %>% 
  group_by(week_alas_link, species) %>% 
  mutate(#lma_all = lma_g_cm2_new,
         lma_g_cm2 = mean(lma_g_cm2_new, na.rm = T)) %>% 
  #filter(lma_g_cm2 < 0.08) %>% 
  select(week, species, lma_g_cm2) %>% 
  distinct() %>% 
  drop_na(lma_g_cm2)  %>%
 # filter(week %in% c(10, 11, 13, 14, 17, 21, 29, 37, 40)) %>% 
  ggplot(aes(x = week_alas_link, 
             y = lma_g_cm2, 
             color = species)) +
  geom_point(size = 3) +
  geom_line() +
  scale_x_continuous(breaks = c(10, 11, 13, 14, 17, 21, 29, 37, 40)) +
  labs(y = "LMA") +
  theme(legend.position = "none", 
        axis.title.y = element_text(size = 20), 
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.x = element_text(hjust=.5, size= 20))
lma_plot
```


```{r, fig.height=2, fig.width=6}
fig_df <- read_csv(here("processed-data", paste0("wp_wc_rwc_",datver,".csv")), show_col_types = F) %>% 
  group_by(week_alas_link, species) %>% 
  mutate(alas_cm2_per_mm2 = mean(alas_cm2_per_mm2, na.rm = T)) %>% 
  select(week, species, alas_cm2_per_mm2) %>% 
  distinct() %>% 
  drop_na(alas_cm2_per_mm2)

unique(fig_df$week)

alas_plot <- fig_df %>% 
  filter(week %in% c(c(10, 11, 13, 14, 17, 21, 29, 37, 40))) %>% 
  ggplot(aes(x = week_alas_link, 
             color = species,
             y = alas_cm2_per_mm2))+
  #geom_hline(yintercept = 0) +
  geom_point(size = 3) +
  geom_line() +
  scale_x_continuous(breaks = c(10, 11, 13, 14, 17, 21, 29, 37, 40)) +
  labs(y = "Al:As") +
  theme(legend.position = "none", 
        axis.title.y = element_text(size = 20), 
        axis.title.x = element_blank(), 
        axis.text.y = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.x = element_text(hjust=.5, size= 20)
        )
alas_plot

ggsave(here("figures", "alas_long_plot"), alas_plot, device = "jpg", width = 12, height = 2, dpi = 300)
```
